### ISSUE TITLE
Error when I'm going to create the module

### ISSUE THREAD

**Issue by Fonsi20** [mstuttgart/vscode-odoo-scaffold#2]
I have Python installed and the odoo-bin path placed in settings.json
My operating system is W10 and I work on Odoo 12 with Python 3.7.3

These are the windows that appear to me:
- New Odoo module create successfully!
- Something went wrong! Please report on GitHub

**Comment by mstuttgart** [comment]
Hi @Fonsi20, you use Vscode in Windows? I can't support Windows, because I develop in Linux only.
This bug must be in path format.

**Comment by mstuttgart** [comment]
@Fonsi20 please, post here you `Python path` and `Odoo bin path`.
