### ISSUE TITLE
issue with creating new module 

### ISSUE THREAD

**Issue by amr-ismaiel** [mstuttgart/vscode-odoo-scaffold#5]
hello 
when i try to make new module option i got two messages 
1- new module created successfully 
2- something went wrong please report on gethub 
i'm using linux mint 19 and vs code portable ,,, odoo 10

**Comment by jwarren4881** [comment]
I am having the same issue. Using VS Code windows 10, Odoo-14

**Comment by mstuttgart** [comment]
@jwarren4881 @amr-ismaiel  Thanks to use vscode-odoo-scaffold!

I update the code in 0.1.4 (https://github.com/mstuttgart/vscode-odoo-scaffold/releases/tag/0.1.4) and fix the bug!

The vscode not active context of virtualenv to odoobin scafflold binary. This cause the bug.

To fix this bug, I added the 'pythonVirtualEnv' parameter: https://github.com/mstuttgart/vscode-odoo-scaffold#settings

This parameter is absolute path of python interpreter inside of virtualenv.

Please, update you version of 'vscode-odoo-scaffold' to **0.1.4.**

**Comment by ibLeDy** [comment]
Usually VSCode already knows the virtualenv that you're using, by adding this setting when you select the workspace's interpreter, to the `settings.json` located at your workspace's `.vscode` folder.
```json
{
    "python.pythonPath": ".venv/bin/python"
}
```

Maybe you could use that path instead, or at least as a default (if it is set), so we don't need to set it manually, but we can change it if we want/need to.

**Comment by mstuttgart** [comment]
Hi @ibLeDy 

The previous version used 'pythonPath', but vscode ended up using the system's standard Python version (even with virtualenv configured as the default interpreter, in the case of Linux) and not virtualenv's Python. This configuration was not working. The solution I found was to create  a new parameter. This avoids confusion when configuring by the user and also reduces the need for maintenance.

**Comment by ibLeDy** [comment]
I would argue that needing to set it _increases_ the need for maintenance, as you have to set it for every workspace, apart from selecting the interpreter, which you always have to. I also would say that finding a way to use `pythonPath` would be better in almost all cases, but that's only my opinion and I could be mistaken.

With that said I understand this change as it solves a problem, so that's always great :)

**Comment by mstuttgart** [comment]
Thanks for the sugestion! I only use an odoo workspace for development, so I have to do this configuration only once. I hadn’t analyzed those points you mentioned. Anyway, at the moment I'm focused on other projects, so I just wanted to fix this bug so people could use the extension without any problems. Maybe later I will be able to improve the extension. 🙏🏻

**Comment by jwarren4881** [comment]
Thanks so much for updating this package! I don't get the error anymore but now clicking 'New Odoo Module' in VSCode just doesn't do anything....

I'm thinking there is something I don't have configured correctly. Here is my settings.json:

`  "odooScaffold.odooTemplatePath": "${workspaceRoot}/user",`
`    "odooScaffold.pythonVirtualEnv": "${workspaceRoot}/.venv/ScriptsScripts",`
`    "odooScaffold.odooBinPath": "C:\\Users\\jwarr\\Documents\\odoo-github\\odoo-bin"`

Am I missing something?

**Comment by mstuttgart** [comment]
Hi! @jwarren4881 

You `pythonVirtualEnv` is incorrect. You need to seed absolute path of python virtualenv and template file:

```
  "pythonVirtualEnv": "absolute/path/to/virtualenv/bin/python",
  "odooTemplatePath": "absolute/path/to/moduletemplate"
```

On Windows it would look like this I think

```
  "pythonVirtualEnv": "absolute\path\to\virtualenv\bin\python",
  "odooTemplatePath": "absolute\path\to\moduletemplate" 
```

Unfortunately at the moment I am not able to fully support the Windows version to test.
