### ISSUE TITLE
Include a template parameter

### ISSUE THREAD

**Issue by pablomartinezgil** [mstuttgart/vscode-odoo-scaffold#6]
Hi.

It is possible to add a parameter to use in case you want to create the scaffold with your own template instead of the odoo template? (i.e with your personalized manifest file, directories, etc.).

It should be used with -t option of the scaffold command if this parameter is set or something like that.

**Comment by mstuttgart** [comment]
Hi @pablomartinezgil . 
This feature is planned for a future release! :grin:
