### ISSUE TITLE
error setting pythonVirtualEnv parameter

### ISSUE THREAD

**Issue by janderbenitez** [mstuttgart/vscode-odoo-scaffold#9]
Hi everyone. Im struggling setting up this extension. 
Well im on Windows using VS Code connected to Linux Development Server throw SSH

![image](https://user-images.githubusercontent.com/24375519/172257757-2b2680d9-2302-4fab-a1d6-96def9278430.png)

So As you can see in the screenshot python extension show python global environment wich is /bin/python3
But when i put this in parameter still have error 

pythonVirtualEnv not set in settings. Please add it

Anyone can help me? Thanks in advance

**Comment by mstuttgart** [comment]
@janderbenitez the virtualenv path must be _absolute_ _path_ (in Windows you need to use Windows path forma 'C:/path .., I guess). I use this extension in a local virtualenv and work.

**Comment by janderbenitez** [comment]
> @janderbenitez the virtualenv path must be _absolute_ _path_ (in Windows you need to use Windows path forma 'C:/path .., I guess). I use this extension in a local virtualenv and work.

Hi mstuttgart thanks for reply. Well im on windows but server is linux. Remember wich i connect throw SSH to Ubuntu Server 22.04 there is the app dont use docker is on premise. 

If i surf to /bin i could find python folders wich i set in extension api but i doesnt work each one

![image](https://user-images.githubusercontent.com/24375519/172612211-ed9e254f-690c-404c-954e-bb8b53a255a4.png)

**Comment by mstuttgart** [comment]
@janderbenitez sorry, my mistake. I set virtualenv in vscode and set the pythonPath as:

> /home/michell/odoo/.venv/bin/python

I need to test using pyhon exec in /bin folder.
